script:
- |
  git config user.name "Sync agent"
  git config user.email "tyriar@tyriar.com"
  git remote add upstream https://$GITHUB_API_KEY@github.com/Tyriar/wiki-sync-example.wiki.git > /dev/null 2>&1
  git fetch upstream
  git push upstream HEAD:master
env:
  matrix:
  - secure: kQEpHY5cxwYUorii3J0VywJeL2+MHHkq5dnEin/lxTVcAyPywrC7dqg0cblVdfnazJ17ba+kfpZcrx4o1CIZDy1wuxrmomT1SsOKhGYMUbkGldsMmtbtuFBSXvOYQQuDJPqNEmhSjbHzEXYPVv2PoM+G/Y/iTcP58uNpuzYNowO+LQ7WZiyzG2YxW/6NVbhUodSLYDv5PdLxP7Ftn30Ka+8l7IoSEh+oZsz2Ssj0koiYCGNBIlVdW8b74dzgJBvvr+XwGG90DP92+AS8bXqOO6Kv/26jlrAFgMresW2gqnK7vaxVFHLjEvsIirmg+QIFaWivTPO2Sa9dYay7BoKcagPmDdjyt2LXeJ2l6/TPzZPD0rgvdqmStnLqHJseuF33pPAkM6/gKSZ9jhiMD32Oshy9F35/Ielip4eru07nRW4GR8rT481qzBpKZxRMr63eauGG+p0Bx1no8zjycUhXORWCdWTH9IUWwwuSSbCuV0rMARMqwU7T/jm/5vR8aeWGYUNA+m91bwrmQ/uonJ/XjdFfnwUTysnBlP/XG3T7uKsasz+AfjqPkr3wKa6AVJ2wTWZBb/MhPq/mKl2Huo8a5U0YwtmP5fRPLbbqWP8rrHXXuO2JE+kMPZPiD5aiNxBzehkNQx0LIwCRh0iwV1cJYUrseewkYVkIexBUZUq/rZQ=
